export const BOOKING_CAR_REQUEST = "views/booking/BOOKING_REQUESTED"
export const CLEAR_BOOKING_CAR = "views/booking/CLEAR_BOOKING_CAR"
export const CREATE_BOOKING_CAR = "views/booking/CREATE_BOOKING_CAR"
export const CREATE_BOOKING_CAR_WITHOUT_DRIVER = "views/booking/CREATE_BOOKING_CAR_WITHOUT_DRIVER"